### ISSUE TITLE
Not working on Android / Chrome

### ISSUE THREAD

**Issue by slibert** [bdunn44/MEJS-Vaadin#2] opened 2015-01-07 10:59 UTC
It's seems that it does not work on Android / Chrome Browser.
I tried a small project (that was working with Vaadin "Audio" component).

View is loading (blank page), showing loading indicator on top of page, but loads forever...

Same behavior with online demo http://bdunn.jelastic.servint.net/Vaadin-Addon-Demo/?a=MejsPlayer

If it can help, I can see the following warning in my logs. Not sure if it's related.

janv. 07, 2015 11:51:47 AM com.vaadin.ui.ConnectorTracker unregisterConnector
WARNING: Tried to unregister MediaComponent (9) which is not registered
janv. 07, 2015 11:51:47 AM com.vaadin.ui.ConnectorTracker registerConnector
WARNING: An already registered connector was registered again: MediaComponent (9)

Regards

**Comment by bdunn44** [comment] 2015-01-07 15:13
I do know that there are browser compatibility issues in the current version, however I'm not sure what the cause is and I don't have time to dig into this at the moment. Please feel free to tackle this and submit a pull request if you're up to it!

Bryson

**Comment by bdunn44** [comment] 2016-06-11 15:47
Just checked the demo app on Android/Chrome and everything seems to be working. Plugins are not supported, but HTML5 file formats (ogg, mp4, mp3, etc.) are working. Closing this issue.

**Closed as completed by bdunn44** 2016-06-11 15:47 UTC
Labels: bug, help wanted
