### ISSUE TITLE
Download File in Firefox

### ISSUE THREAD

**Issue by SimonC-24** [bdunn44/MEJS-Vaadin#4] opened 2015-04-27 23:19 UTC
I have uninstalled Adobe Flash Player as I want my video to be played with HTML5.

I am trying to play youtube sample on http://bdunn.jelastic.servint.net/Vaadin-Addon-Demo/?a=MejsPlayer and all I get is blank screen and Download File link.

It works in Chrome as there is Flash Played integrated in it.

Simon

**Comment by bdunn44** [comment] 2015-04-28 01:13
Thanks for reporting this - I think the Media Element JS YouTube plugin isn't being loaded properly so it is played using flash. I've already written code for a fix - I will test it and release a patch.

-Bryson

**Comment by bdunn44** [comment] 2015-04-28 02:27
Fixed in 1.2.6 and 1.2.7

**Closed as completed by bdunn44** 2015-04-28 02:27 UTC

**Comment by SimonC-24** [comment] 2015-04-28 02:47
I am using vaadin 7.3.8 and therefore mejs-player-1.2.6 and getting this in debug mode:

15981ms (TypeError) __gwt$exception: <skipped>: Cannot read property 'apply' of undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: <skipped>: Cannot read property 'apply' of undefined
   at Unknown.JRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@25)
   at Unknown.zRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@155)
   at Unknown.NRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@41806)
   at Unknown.o0b(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@178)
   at Unknown.FOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@204)
   at Unknown.EOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@515)
   at Unknown.ROb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@12800)
   at Unknown.bMb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@106)
   at Unknown.PNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@179)
   at Unknown.SNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@10830)
   at Unknown.ZTb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@222)
   at Unknown.nUb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@14733)
   at Unknown.eval(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@108)
   at Unknown.ro(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@29)
   at Unknown.wo(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@57)
   at Unknown.eval(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@54)
16000ms (TypeError) __gwt$exception: <skipped>: Cannot read property 'apply' of undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: <skipped>: Cannot read property 'apply' of undefined
   at Unknown.JRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@25)
   at Unknown.zRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@155)
   at Unknown.NRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@41806)
   at Unknown.o0b(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@178)
   at Unknown.FOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@204)
   at Unknown.EOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@515)
   at Unknown.ROb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@12800)
   at Unknown.bMb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@106)
   at Unknown.PNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@179)
   at Unknown.SNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@10830)
   at Unknown.ZTb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@222)
   at Unknown.nUb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@14733)
   at Unknown.eval(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@108)
   at Unknown.ro(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@29)
   at Unknown.wo(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@57)
   at Unknown.eval(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@54)
16004ms

and this in layout:

Could not initialize JavaScriptConnector because no JavaScript init function was found. Make sure one of these functions are defined: 
com_kbdunn_vaadin_addons_mediaelement_MediaElementPlayer
com_vaadin_ui_AbstractJavaScriptComponent
com_vaadin_ui_AbstractComponent
com_vaadin_server_AbstractClientConnector.

Any idea, what am I doing wrong?

Simon

**Comment by bdunn44** [comment] 2015-04-28 02:48
I'm not sure about the first part, but the second is because the old javascript file is cached in your browser. Try clearing the cache and see if that works

**Comment by SimonC-24** [comment] 2015-04-28 02:59
I have cleared browser cache, restart server and refresh the page, now getting (in firefox)

33508ms(TypeError) __gwt$exception: <skipped>: p is undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: <skipped>: p is undefined
   at Unknown.com_kbdunn_vaadin_addons_mediaelement_MediaElementPlayer/t.updateSource(Unknown Source)
   at Unknown.JRb(Unknown Source)
   at Unknown.zRb(Unknown Source)
   at Unknown.NRb(Unknown Source)
   at Unknown.o0b(Unknown Source)
   at Unknown.FOb(Unknown Source)
   at Unknown.EOb(Unknown Source)
   at Unknown.ROb(Unknown Source)
   at Unknown.bMb(Unknown Source)
   at Unknown.PNb(Unknown Source)
   at Unknown.SNb(Unknown Source)
   at Unknown.ZTb(Unknown Source)
   at Unknown.nUb(Unknown Source)
   at Unknown.dUb/a.onload<(Unknown Source)
   at Unknown.ro(Unknown Source)
   at Unknown.wo(Unknown Source)
   at Unknown.vo/<(Unknown Source)
   at Unknown.anonymous(Unknown Source)

and (in Chrome)

12969ms (TypeError) __gwt$exception: <skipped>: Cannot read property 'setSource' of undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: <skipped>: Cannot read property 'setSource' of undefined
   at Unknown.t.updateSource(http://localhost:8080/AISVOPAC/VAADIN/addons/mejs-player/mejs-player-connector.js@4)
   at Unknown.JRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@26)
   at Unknown.zRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@155)
   at Unknown.NRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@41806)
   at Unknown.o0b(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@178)
   at Unknown.FOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@204)
   at Unknown.EOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@515)
   at Unknown.ROb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@12800)
   at Unknown.bMb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@106)
   at Unknown.PNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@179)

**Comment by bdunn44** [comment] 2015-04-28 03:00
That definitely looks like a widgetset compilation issue, but this addon doesn't require one. I would suggest re-compiling your widgetset - it may be unrelated.

**Comment by SimonC-24** [comment] 2015-04-28 03:13
After recompiling the widgetset (and clearing the cache again) I still get both errors (in FF in Chrome). Any idea?

**Comment by bdunn44** [comment] 2015-04-28 03:28
Trying to reproduce this. Will let you know

**Comment by SimonC-24** [comment] 2015-04-28 03:42
What surprises me it still WORKS in both browsers (i.e. youtube video is playing), in spite of those errors in ?debug console. Should I be concerned about errors at all?

**Comment by bdunn44** [comment] 2015-04-28 03:53
I see those too when I roll back to 7.3.8 but you're right, everything seems to be working. I would say they're safe to ignore

**Comment by SimonC-24** [comment] 2015-04-28 04:08
I tried with 7.3.9 and also getting those errors. However, it works for now, hope to work without errors when we upgrade to vaadin-7.4.

Thank you very much for your quick response.

Simon

**Comment by bdunn44** [comment] 2015-05-05 02:19
I'm seeing those errors too and they appear to be causing issues in 7.4. Opened issue #5 for this
